import ts from "typescript";
import { describe, expect, it } from "vitest";

import { generateLaunchScript, renderExpr } from "../../src/codegen/typescript";
import { FlowValidationError } from "../../src/errors";
import { ref } from "../../src/flow/refs";
import { createRegistry } from "../../src/registry/registry";
import { FAKE_STEPS } from "../helpers/fake-steps";

const registry = createRegistry(FAKE_STEPS);

const flow = {
  schemaVersion: 1,
  id: "launch",
  name: "Launch",
  description: "Mint then spend.",
  steps: [
    { id: "mint", type: "fake.makeToken", label: "Mint it", params: { symbol: "LB", decimals: 6 } },
    {
      id: "spend",
      type: "fake.useToken",
      params: { tokenId: ref("mint", "tokenId"), amount: 3, memo: `spent ${ref("mint", "tokenId")} today` },
    },
  ],
};

/** Fails on any syntax error so a broken template cannot slip through. */
function assertParses(source: string): void {
  const file = ts.createSourceFile("launch.ts", source, ts.ScriptTarget.ES2022, true, ts.ScriptKind.TS);
  const diagnostics = (file as unknown as { parseDiagnostics: ts.Diagnostic[] }).parseDiagnostics;
  expect(diagnostics.map(d => d.messageText)).toEqual([]);
}

describe("renderExpr()", () => {
  it("renders literals as JSON", () => {
    expect(renderExpr("LB")).toBe('"LB"');
    expect(renderExpr(6)).toBe("6");
    expect(renderExpr(true)).toBe("true");
    expect(renderExpr(null)).toBe("null");
    expect(renderExpr(undefined)).toBe("undefined");
  });

  it("renders whole references as member access", () => {
    expect(renderExpr(ref("mint", "tokenId"))).toBe("mint.tokenId");
  });

  it("renders interpolated strings as template literals with escaping", () => {
    expect(renderExpr(`spent ${ref("mint", "tokenId")} today`)).toBe("`spent ${mint.tokenId} today`");
    expect(renderExpr("`${x}` \\ " + ref("a", "b"))).toBe("`\\`\\${x}\\` \\\\ ${a.b}`");
  });

  it("renders arrays and objects recursively", () => {
    expect(renderExpr(["0.0.1", ref("mint", "tokenId")])).toBe('["0.0.1", mint.tokenId]');
    expect(renderExpr({ tokenId: ref("mint", "tokenId"), "odd-key": 1, empty: {} })).toBe(
      '{ tokenId: mint.tokenId, "odd-key": 1, empty: {} }',
    );
  });
});

describe("generateLaunchScript()", () => {
  const source = generateLaunchScript(flow, registry);

  it("produces syntactically valid TypeScript", () => {
    assertParses(source);
  });

  it("is deterministic", () => {
    expect(generateLaunchScript(flow, registry)).toBe(source);
  });

  it("declares one const per step, wrapped in the step helper, in flow order", () => {
    const mintAt = source.indexOf('const mint = await step("mint", async () => {');
    const spendAt = source.indexOf('const spend = await step("spend", async () => {');
    expect(mintAt).toBeGreaterThan(0);
    expect(spendAt).toBeGreaterThan(mintAt);
  });

  it("applies schema defaults for omitted params while keeping references", () => {
    const defaulted = generateLaunchScript(
      { ...flow, steps: [{ id: "mint", type: "fake.makeToken", params: { symbol: "LB" } }, flow.steps[1]] },
      registry,
    );
    expect(defaulted).toContain('return await fakeMakeToken("LB", 8);');
    expect(defaulted).toContain("fakeUseToken(mint.tokenId, 3,");
  });

  it("passes literals, references and interpolations through to step bodies", () => {
    expect(source).toContain('return await fakeMakeToken("LB", 6);');
    expect(source).toContain("return await fakeUseToken(mint.tokenId, 3, `spent ${mint.tokenId} today`);");
  });

  it("collects and deduplicates imports, sorted by specifier", () => {
    const importLines = source.split("\n").filter(line => line.startsWith("import "));
    expect(importLines).toEqual([
      'import { fakeMakeToken, fakeUseToken } from "./fake-sdk";',
      'import { hederaContextFromEnv } from "@sh/launchblocks";',
    ]);
  });

  it("documents the flow and its network in the header and bootstraps the operator", () => {
    expect(source).toMatch(/^\/\*\*\n \* Generated by LaunchBlocks from flow "launch" \(Launch\)\./);
    expect(source).toContain(" * Mint then spend.");
    expect(source).toContain('hederaContextFromEnv(process.env, { network: "testnet" })');
    expect(source).toContain("// 1. mint: Mint it (fake.makeToken)");
    expect(source).toContain("// 2. spend: fake.useToken");
    expect(source).toContain('console.log("Flow complete", { mint, spend });');
  });

  it("honours the core module and header options", () => {
    const custom = generateLaunchScript(flow, registry, {
      coreModule: "../src",
      headerLines: ["Source: flows/launch.json"],
    });
    expect(custom).toContain('import { hederaContextFromEnv } from "../src";');
    expect(custom).toContain(" * Source: flows/launch.json");
    assertParses(custom);
  });

  it("refuses invalid flows", () => {
    expect(() => generateLaunchScript({ ...flow, steps: [] }, registry)).toThrowError(FlowValidationError);
  });
});
