import { z } from "zod";

import { createPoolWithHbar } from "../../saucerswap/pool";
import { defineStep } from "../../registry/define-step";
import { CATEGORY_COLOUR, PositiveAmountSchema, TokenIdSchema } from "../shared";

export const saucerswapCreatePool = defineStep({
  type: "saucerswap.createPool",
  input: z.object({
    tokenId: TokenIdSchema,
    tokenAmount: PositiveAmountSchema,
    hbarAmount: PositiveAmountSchema,
    slippageBps: z.number().int().min(0).max(9999).default(100),
    deadlineSeconds: z.number().int().min(30).max(3600).default(120),
    feeBufferBps: z.number().int().min(0).max(10_000).default(200),
    gasLimit: z.number().int().min(500_000).max(15_000_000).optional(),
    createPairGasLimit: z.number().int().min(1_000_000).max(15_000_000).optional(),
  }),
  output: z.object({
    tokenId: z.string(),
    pairId: z.string().nullable(),
    pairEvmAddress: z.string().nullable(),
    lpTokenId: z.string().nullable(),
    liquidity: z.string(),
    transactionId: z.string(),
    createPairTransactionId: z.string(),
    allowanceTransactionId: z.string(),
    tokenAmountUnits: z.string(),
    hbarAmountTinybar: z.string(),
    liquidityUnits: z.string(),
    creationFeeHbar: z.string(),
    creationFeePaidHbar: z.string(),
    gasUsed: z.number().int(),
    openingPriceHbar: z.string(),
    poolUrl: z.string(),
  }),
  outputExample: {
    tokenId: "0.0.6512345",
    pairId: "0.0.6512500",
    pairEvmAddress: "0xfe7cc3ceb7b1128bfc3889184e2d5561bf74bfb3",
    lpTokenId: "0.0.6512501",
    liquidity: "44.72135954",
    transactionId: "0.0.4242@1758500070.000000001",
    createPairTransactionId: "0.0.4242@1758500068.000000001",
    allowanceTransactionId: "0.0.4242@1758500069.000000001",
    tokenAmountUnits: "10000000000000",
    hbarAmountTinybar: "2000000000",
    liquidityUnits: "4472135954",
    gasUsed: 480000,
    creationFeeHbar: "25.95166934",
    creationFeePaidHbar: "26.47070273",
    openingPriceHbar: "0.0002",
    poolUrl: "https://testnet.saucerswap.finance/liquidity/0.0.6512500",
  },
  ui: {
    label: "Seed SaucerSwap pool",
    category: "saucerswap",
    colour: CATEGORY_COLOUR.saucerswap,
    tooltip: "Create the token's first SaucerSwap V1 pool against HBAR. The two amounts set the opening price.",
    fields: [
      { key: "tokenId", label: "Token", kind: "tokenId" },
      { key: "tokenAmount", label: "Tokens to deposit", kind: "amount", help: "Whole tokens" },
      {
        key: "hbarAmount",
        label: "HBAR to deposit",
        kind: "amount",
        help: "Sets the opening price together with the token amount",
      },
      {
        key: "slippageBps",
        label: "Slippage (bps)",
        kind: "number",
        help: "100 = 1% tolerated shortfall",
        advanced: true,
      },
      { key: "deadlineSeconds", label: "Deadline (s)", kind: "number", advanced: true },
      {
        key: "gasLimit",
        label: "Gas limit",
        kind: "number",
        help: "Defaults to 5,000,000; the association path is gas-hungry",
        advanced: true,
      },
    ],
    outputs: [
      { key: "pairId", label: "Pool", kind: "contractId" },
      { key: "lpTokenId", label: "LP token", kind: "tokenId" },
      { key: "liquidity", label: "LP tokens received", kind: "amount" },
      { key: "createPairTransactionId", label: "Create pair transaction", kind: "transactionId" },
      { key: "transactionId", label: "Deposit transaction", kind: "transactionId" },
      { key: "openingPriceHbar", label: "Opening price (HBAR)", kind: "amount" },
      { key: "creationFeeHbar", label: "Pool creation fee (HBAR)", kind: "amount" },
    ],
  },
  docs: {
    summary: "Create the token's first SaucerSwap V1 liquidity pool against HBAR, making it tradeable.",
    details: [
      "This is the step that turns a token into a market. The deposits set the opening price, so the step is",
      "built to make that price come out exactly as specified.",
      "",
      "It creates the pool in two calls rather than the router's one-call `addLiquidityETHNewPool`. That",
      "function deposits all of `msg.value` beyond the creation fee it computes at consensus, and the fee is",
      "priced in tinycents at an exchange rate the caller can only estimate, so any estimate error lands in",
      "the pool: a measured run asked for 10 HBAR and deposited 10.32, opening 3.2% high. Instead:",
      "",
      "1. `factory.createPair`, paying the quoted fee (at the higher of the mirror node's current and next",
      "   rates) plus `feeBufferBps`. The factory forwards any excess to SaucerSwap's rent payer, so it never",
      "   reaches the pool; a short fee reverts here, before anything is deposited.",
      "2. An ERC-20 `approve` for the router, then `router.addLiquidityETH` with exactly the HBAR requested.",
      "",
      "LP tokens go to the operator's **EVM alias**: alias-created ECDSA accounts reject the long-zero",
      "address with INVALID_ALIAS_KEY on the final transfer, which the contracts report only as",
      '"Safe token transfer failed!". Gas defaults come from measured runs; the documented 3,200,000 is too',
      "low. Existing pools are refused up front.",
      "",
      "The LP token is an HTS token the pair creates, a separate entity from the pair contract; `lpTokenId`",
      "comes from the pair's `lpToken()`, and `liquidity` is what the operator received, in whole LP tokens.",
    ].join("\n"),
    hederaServices: ["HTS", "SmartContract", "MirrorNode"],
    integrations: ["SaucerSwap"],
  },
  execute: (input, ctx) => createPoolWithHbar(ctx.hedera, input, ctx.signal),
  codegen: ctx => {
    ctx.addImport(ctx.coreModule, "createPoolWithHbar");
    return {
      body: [
        `return await createPoolWithHbar(ctx, {`,
        `  tokenId: ${ctx.expr("tokenId")},`,
        `  tokenAmount: ${ctx.expr("tokenAmount")},`,
        `  hbarAmount: ${ctx.expr("hbarAmount")},`,
        `  slippageBps: ${ctx.expr("slippageBps")},`,
        `  deadlineSeconds: ${ctx.expr("deadlineSeconds")},`,
        `  feeBufferBps: ${ctx.expr("feeBufferBps")},`,
        `  gasLimit: ${ctx.expr("gasLimit")},`,
        `  createPairGasLimit: ${ctx.expr("createPairGasLimit")},`,
        `});`,
      ].join("\n"),
    };
  },
});
