import { findRefs, isPlainObject, parseRef, resolveRefs } from "../flow/refs";
import type { ZodType } from "zod";

import type { Flow } from "../flow/schema";
import type { StepRegistry } from "../registry/registry";
import type { CodegenContext } from "../registry/types";

export type CodegenOptions = {
  /** Module the generated file imports core helpers from. */
  coreModule?: string;
  /** Extra comment lines for the file header (e.g. a timestamp or source path). */
  headerLines?: readonly string[];
};

const DEFAULT_CORE_MODULE = "@sh/launchblocks";

/**
 * Render a validated flow as a standalone TypeScript script that performs
 * the same steps with the Hedera SDK. Each step's body runs inside its own
 * async closure and its returned outputs become a `const` named after the
 * step id, so later steps reference `createToken.tokenId` exactly as the
 * flow JSON did with `{{steps.createToken.tokenId}}`.
 */
export function generateLaunchScript(document: unknown, registry: StepRegistry, options: CodegenOptions = {}): string {
  const flow = registry.validateFlow(document);
  const coreModule = options.coreModule ?? DEFAULT_CORE_MODULE;
  const imports = new ImportCollector();
  imports.add(coreModule, "hederaContextFromEnv");

  /** Example outputs of earlier steps, so defaults can be computed with references in place. */
  const exampleOutputs: Record<string, Record<string, unknown>> = {};

  const sections = flow.steps.map((step, index) => {
    const definition = registry.get(step.type);
    const params = paramsWithDefaults(step.params, definition.input, exampleOutputs);
    exampleOutputs[step.id] = definition.outputExample;
    const ctx: CodegenContext = {
      stepId: step.id,
      expr: key => renderExpr(params[key]),
      addImport: (specifier, ...names) => imports.add(specifier, ...names),
    };
    const fragment = definition.codegen(ctx);
    const title = step.label ? `${step.label} (${step.type})` : step.type;
    return [
      `  // ${index + 1}. ${step.id}: ${title}`,
      `  const ${step.id} = await step("${step.id}", async () => {`,
      indent(fragment.body.trim(), 4),
      `  });`,
    ].join("\n");
  });

  const summary = flow.steps.map(step => `${step.id}`).join(", ");

  return [
    header(flow, options.headerLines ?? []),
    imports.render(),
    "",
    STEP_HELPER,
    "",
    `async function main(): Promise<void> {`,
    `  const ctx = hederaContextFromEnv(process.env, { network: ${JSON.stringify(flow.network)} });`,
    `  const { client, operatorId, operatorKey } = ctx;`,
    `  console.log(\`Running flow ${flow.id} on ${flow.network} as \${operatorId.toString()}\`);`,
    "",
    sections.join("\n\n"),
    "",
    `  console.log("Flow complete", { ${summary} });`,
    `  client.close();`,
    `}`,
    "",
    `main().catch(error => {`,
    `  console.error(error);`,
    `  process.exitCode = 1;`,
    `});`,
    "",
  ].join("\n");
}

/**
 * Apply the input schema's defaults without losing references: parse a copy
 * where references are replaced by example outputs, then let the original
 * (reference-bearing) values win for every key the author wrote.
 */
function paramsWithDefaults(
  params: Record<string, unknown>,
  input: ZodType,
  exampleOutputs: Record<string, Record<string, unknown>>,
): Record<string, unknown> {
  const parsed = input.parse(resolveRefs(params, exampleOutputs));
  return isPlainObject(parsed) ? { ...parsed, ...params } : params;
}

function header(flow: Flow, extra: readonly string[]): string {
  const lines = [
    `Generated by LaunchBlocks from flow "${flow.id}" (${flow.name}).`,
    ...(flow.description ? ["", flow.description] : []),
    "",
    "Regenerate from the flow JSON instead of editing by hand.",
    `Requires HEDERA_OPERATOR_ID and HEDERA_OPERATOR_KEY for ${flow.network}.`,
    ...(extra.length ? ["", ...extra] : []),
  ];
  return ["/**", ...lines.map(line => (line ? ` * ${line}` : " *")), " */"].join("\n");
}

const STEP_HELPER = `/** Runs one step, printing its timing and outputs. */
async function step<T>(id: string, run: () => Promise<T>): Promise<T> {
  const startedAt = Date.now();
  console.log(\`▶ \${id}\`);
  try {
    const outputs = await run();
    console.log(\`✔ \${id} (\${Date.now() - startedAt} ms)\`, outputs);
    return outputs;
  } catch (error) {
    console.error(\`✖ \${id} failed\`, error);
    throw error;
  }
}`;

class ImportCollector {
  private readonly bySpecifier = new Map<string, Set<string>>();

  add(specifier: string, ...names: string[]): void {
    const set = this.bySpecifier.get(specifier) ?? new Set<string>();
    names.forEach(name => set.add(name));
    this.bySpecifier.set(specifier, set);
  }

  render(): string {
    return [...this.bySpecifier.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([specifier, names]) => `import { ${[...names].sort().join(", ")} } from ${JSON.stringify(specifier)};`)
      .join("\n");
  }
}

/**
 * TypeScript expression for a flow param value. Whole references become
 * `<stepId>.<key>`, interpolated strings become template literals, and
 * arrays/objects are rendered recursively so nested references survive.
 */
export function renderExpr(value: unknown): string {
  if (value === undefined) return "undefined";
  if (typeof value === "string") {
    const whole = parseRef(value);
    if (whole) return `${whole.stepId}.${whole.key}`;
    if (findRefs(value).length === 0) return JSON.stringify(value);
    return renderTemplateLiteral(value);
  }
  if (Array.isArray(value)) {
    return `[${value.map(renderExpr).join(", ")}]`;
  }
  if (isPlainObject(value)) {
    const entries = Object.entries(value).map(([key, item]) => `${renderKey(key)}: ${renderExpr(item)}`);
    return entries.length ? `{ ${entries.join(", ")} }` : "{}";
  }
  return JSON.stringify(value);
}

function renderTemplateLiteral(value: string): string {
  const pattern = /\{\{\s*steps\.([a-z][a-zA-Z0-9]*)\.([a-z][a-zA-Z0-9]*)\s*\}\}/g;
  let out = "`";
  let last = 0;
  for (const match of value.matchAll(pattern)) {
    out += escapeTemplateText(value.slice(last, match.index));
    out += `\${${match[1]}.${match[2]}}`;
    last = match.index + match[0].length;
  }
  out += escapeTemplateText(value.slice(last));
  return out + "`";
}

function escapeTemplateText(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
}

function renderKey(key: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(key) ? key : JSON.stringify(key);
}

function indent(text: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return text
    .split("\n")
    .map(line => (line.trim() ? pad + line : line))
    .join("\n");
}
